# Задание 3: Nginx access-log -> Logstash -> Elasticsearch
input {
  file {
    path => "/var/log/nginx/hw_access.log"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/sincedb_nginx"
    mode => "tail"
  }
}

filter {
  grok {
    match => { "message" => "%{COMBINEDAPACHELOG}" }
  }
  date {
    match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss Z" ]
    target => "@timestamp"
  }
  mutate {
    convert => { "response" => "integer" }
    convert => { "bytes" => "integer" }
  }
  geoip {
    source => "clientip"
    target => "geoip"
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "nginx-logstash-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
